config/routes.rb
Rails.application.routes.draw do

  root 'school_classes#index'

  resources :schools
  resources :school_classes
  resources :homeworks
  resources :students
  resources :teachers
  resources :notifications

end

app/models/homework.rb
class Homework < ActiveRecord::Base

  belongs_to :school_class
  belongs_to :teacher
  belongs_to :student

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :school
  belongs_to :student
  belongs_to :teacher
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :teachers
  has_many :students
  has_many :notifications
  has_many :subjects
  has_many :school_classes
  has_many :homeworks
end

app/models/school_class.rb
class SchoolClass < ActiveRecord::Base
  belongs_to :school
  belongs_to :homework
  belongs_to :subject
  belongs_to :student
  belongs_to :teacher
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school

  belongs_to :subject
  has_many :school_classes
  has_many :homeworks

  has_many :notifications
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :school

  has_many :school_classes
  has_many :teachers
  has_many :students

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  belongs_to :subject

  has_many :school_classes

  has_many :homeworks
  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  def index
    @homeworks = Homework.all
  end

  def show
    @homework = Homework.find(params[:id])
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])
  end
end

app/controllers/school_classes_controller.rb
class SchoolClassesController < ApplicationController
  def index
    @schoolClasses = SchoolClass.all
  end

  def show
    @schoolClass = SchoolClass.find(params[:id])
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def show
    @school = School.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/homeworks/index.html.erb
<h1>Домашние задания</h1>
<ul>
  <% @homeworks.each do |homework| %>
      <li><%= link_to homework.name, homework %></li>
  <% end %>
</ul>

app/views/homeworks/show.html.erb
<p><%= link_to '< Все Задания', homeworks_path %></p>
<h1><%= @homework.name %></h1>
<p>Предмет: <%= @homework.school_class.name %></p>
<p>Задание: <%= @homework.description %></p>

app/views/notifications/index.html.erb
<h1>Доска объявлений</h1>

<ul>
  <% @notifications.each do |notification| %>
    <li><%= link_to notification.theme, notification %></li>
  <% end %>
</ul>

app/views/notifications/show.html.erb
<p><%= link_to '< Все Уведомления', notifications_path %></p>

<h1><%= @notification.theme %></h1>
<p>
  <%= @notification.notificationText %>
</p>

app/views/school_classes/index.html.erb
<h1>Расписание</h1>
<ul>
  <% @schoolClasses.each do |schoolClass| %>
      <li><%= link_to schoolClass.name, schoolClass %></li>
  <% end %>
</ul>

app/views/school_classes/show.html.erb
<p><%= link_to '< Расписание', school_classes_path %></p>

<h1><%= @schoolClass.name %></h1>
<p>Преподаватель: <%= @schoolClass.teacher.fname %> <%= @schoolClass.teacher.lname %></p>
<p>Домашнее задание <%= @schoolClass.homework.name %></p>

app/views/schools/index.html.erb
<h1>Список Школ</h1>
<ul>
  <% @schools.each do |school| %>
    <li><%= link_to school.name, school %></li>
  <% end %>
</ul>

app/views/schools/show.html.erb
<p><%= link_to '< Все Школы', schools_path %></p>

<h1><%= @school.name %></h1>
<p>
  <%= @school.description %>
</p>
<p>Все преподаватели
</p>
<ul>
  <% @school.teachers.each do |teacher| %>
      <li><%= link_to teacher.fname, teacher %></li>
  <% end %>
</ul>

app/views/students/index.html.erb
<h1>Мои одноклассники</h1>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.fname, student %></li>
  <% end %>
</ul>

app/views/students/show.html.erb
<p><%= link_to '< Все одноклассники', students_path %></p>

<h1><%= @student.fname %> <%= @student.lname %></h1>
<p>
</p>

app/views/teachers/index.html.erb
<h1>Мои Учителя</h1>

<ul>
  <% @teachers.each do |teacher| %>
    <li><%= link_to teacher.fname, teacher %></li>
  <% end %>
</ul>

app/views/teachers/show.html.erb
<p><%= link_to '< Все преподаватели', teachers_path %></p>

<h1><%= @teacher.fname %> <%= @teacher.lname %></h1>
<p>Все предметы
</p>
<ul>
  <% @teacher.school_classes.each do |schoolClass| %>
      <li><%= link_to schoolClass.name, schoolClass %></li>
  <% end %>
</ul>